python main.py \
--exp_name  Galaxy10-DEC-cont/transformer/mlp_8_layer/image_loss-NF_128 \
--ngpus 2 \
--yaml_file  \
--loss_type spectral \
--num_fourier 128 \
--input_size 256 \
--dataset Galaxy10_DECals \
--data_path_cont /datasets/deepuv/polarrec/eht_cont_200im_Galaxy10_DECals_full.h5 \
--data_path_imgs /datasets/deepuv/polarrec/Galaxy10_DECals.h5 \
--dataset_path   /datasets/deepuv/polarrec/eht_grid_128FC_200im_Galaxy10_DECals_full.h5 \
